### ISSUE TITLE
Is it possible to start a dedicated server?

### ISSUE THREAD

**Issue by botzill** [ovh/terraform-provider-ovh#137]
Hi.

Currently I don't see if using the provider we can start a dedicated server?

Thx.

**Comment by yanndegat** [comment]
hi @botzill 

currently: 
- you cannot order a dedicated server, you have to order it and have available on your account
- once it's available, you can reboot it or launch "install tasks" based on custom installation templates

here-s an example:

https://github.com/ovh/terraform-ovh-commons/blob/master/examples/k8s-sd-openstack/modules/baremetal-hosts/main.tf


does it answer your question ?

**Comment by botzill** [comment]
I see.

I thought I can automate the ordering as well? Because we may need multiple servers and some times we will switch off few and start other when needed. Do I need to manually manage all this?

**Comment by yanndegat** [comment]
yes, you cannot order servers automatically through the provider.
