### ISSUE TITLE
Does not work with Kimsufi-EU (or any other?)

### ISSUE THREAD

**Issue by joekinley** [ovh/terraform-provider-ovh#147]
### Terraform Version
```
$ terraform -v
Terraform v0.12.28
+ provider.ovh v0.8.0
```

### Affected Resource(s)
- ovh_dedicated_server

### Terraform Configuration Files
```hcl
provider "ovh" {
  endpoint = "kimsufi-eu"
}

data "ovh_dedicated_server" "kimsufi" {
  service_name = "my-service-name"
}
```

### Error Message
```
Error: kimsufi-eu must be one of map[string]string{"kimsufi-ca":"https://ca.api.kimsufi.com/1.0", "kimsufi-eu":"https://eu.api.kimsufi.com/1.0", "ovh-ca":"https://ca.api.ovh.com/1.0", "ovh-eu":"https://eu.api.ovh.com/1.0", "ovh-us":"https://api.us.ovhcloud.com/1.0", "runabove-ca":"https://api.runabove.com/1.0", "soyoustart-ca":"https://ca.api.soyoustart.com/1.0", "soyoustart-eu":"https://eu.api.soyoustart.com/1.0"} endpoints


  on main.tf line 1, in provider "ovh":
   1: provider "ovh" {

```
### Expected Behavior
Should have worked with the specified endpoint configuration.

### Actual Behavior
It complains that the endpoint configuration is not correct.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Account setup for ovh-cli is properly set up and works.

**Comment by RealOrangeOne** [comment]
I too get this issue, but without the CLI setup locally (it seems to be deprecated anyway).

Changing the "endpoint" to something else (`ovh-eu`) works fine, so it's definitely something kimsufi specific.

**Comment by pleandre** [comment]
Hello,

I am having the same issue with the current v0.9.1 release.
@yanndegat could you release a new tag / version of the provider with this change ?
I think it should fix my issues.

Thank you,
Pierre

**Comment by yanndegat** [comment]
hi pleandre

WIP

go a lot of stuff/fix/cleanup to do before releasing, should be ready in a few days
