### ISSUE TITLE
ovh-cli is archived

### ISSUE THREAD

**Issue by telenieko** [ovh/terraform-provider-ovh#161]
Hi,

The documentation says:

> It is recommend to install [ovh-cli](https://github.com/ovh/ovh-cli) to handle and manage all your secret keys.

But [ovh/ovh-cli](https://github.com/ovh/ovh-cli) is an archived project with no commit since 2017. Please amend with instructions on how to acquire the credentials without ovh-cli (or have the provider do the authentication flow like other providers do).

thanks!

**Comment by guillermo-menjivar** [comment]
I am in the predicament, @telenieko how were you able to generate credentials without using the `ovh-cli`?

**Comment by yanndegat** [comment]
hi 

thank you for reporting this

we're going to spend some time on the provider in the next couple of weeks to fix this issue and clean the backlog of issues & PRs
but we first have to rebuild a proper CI system (since the switch to the terraform registry has deprecated the internal hashicorp ci for non official providers)

**Comment by telenieko** [comment]
> I am in the predicament, @telenieko how were you able to generate credentials without using the `ovh-cli`?

You can do it from the Web: https://docs.ovh.com/gb/en/customer/first-steps-with-ovh-api/ 

> Requesting an authentication token from OVH
> Now that you have your keys, you can request a token from OVH to enable you to make requests to the API (...)

Then on `~/.ovh.conf` I have:

```ini
[default]
endpoint=ovh-eu

[ovh-eu]
application_key=SECRET
application_secret=SECRET
consumer_key=SECRET
```

It was some time ago so I don't remember the exact steps.

**Comment by amstuta** [comment]
Closing this issue, doc has been updated since then.
