### ISSUE TITLE
OVH vs OpenStack provider

### ISSUE THREAD

**Issue by ncfrak** [ovh/terraform-provider-ovh#167]
Hello,

I can't find in which case should I use the OVH or the OpenStack provider.

Is there anywhere a note on that ?

For example, I need to create a network. For this, I can use openstack_networking_network_v2 or ovh_cloud_network_private.

Maybe there is a difference between the 2, but it is not clear for me what would it be.

**Comment by yanndegat** [comment]
hi @ncfrak 

historically, you couldn't create openstack networks through the openstack API provided by ovh

then it has been enabled, but you still couldn't specify a vlan id in your network to be able to have the same L2 across multiple openstack regions.

now that all of this is possible directly through the openstack api, the preferred way for openstack networking is the openstack provider

**Comment by ncfrak** [comment]
Hi @yanndegat 
Thank you for your answer.

How can we know which provider should we use ?
I suppose some things needs to be done with the OVH provider, but which ones ?

Thank you !

**Comment by yanndegat** [comment]
no, now you can do everything through the openstack provider

**Comment by ncfrak** [comment]
Thank you, case closed!

**Comment by ncfrak** [comment]
Following my question on the same topic.

And how about creating a vRack with the OpenStack provider ?

**Comment by yanndegat** [comment]
@ncfrak it probably means that you haven't ordered a Vrack and attached it to your public cloud project.

here's the snippet to create a vrack within a specific vlan id through the openstack provider
```
resource "openstack_networking_network_v2" "vrack" {
  name           = var.name
  admin_state_up = "true"

  value_specs = var.vlan_id == "" ? {} : {
    "provider:network_type"    = "vrack"
    "provider:segmentation_id" = var.vlan_id
  }
}


```

**Comment by pc-jedi** [comment]
@yanndegat is it required to use `value_specs` rather then `segments` to create a vrack inside a vlan id?
