### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pleandre** [ovh/terraform-provider-ovh#168]
Hi Everyone,

Would it be possible to create a new tag / release.
I am facing the same issue as #147 (issue fixed now but not part of the last release v0.9.1)
The last release is from August 28. I have compiled the provider and did some tests, everything works properly locally.
However, for CI / CD I use a gitlab runner, it would be easier if a new version was released for my runner to pull it.

Thank you,
Pierre

**Comment by pgaxatte** [comment]
v0.10.0 has been released on December 7th and should fix your issue.
