### ISSUE TITLE
Terraform provider 0.10.0 : Error: section "ovh-eu" does not exist

### ISSUE THREAD

**Issue by laurentgrangeau** [ovh/terraform-provider-ovh#179]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.14.0
+ provider registry.terraform.io/ovh/ovh v0.10.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.33.0

### Affected Resource(s)
- provider

### Terraform Configuration Files
```hcl
provider "ovh" {
  endpoint           = "ovh-eu"
  application_key    = "xxx"
  application_secret = "xxx"
  consumer_key       = "xxx"
}
```

### Debug Output
https://gist.github.com/laurentgrangeau/83952fc99ee9beb5d4e35d76115755a5

### Expected Behavior
Terraform apply the requested resources

### Actual Behavior
An error message appear when I use the 0.10.0 provider

### Steps to Reproduce
1. `terraform apply`

**Comment by yanndegat** [comment]
hi @laurentgrangeau 

thank you for reporting this issue

i'm not able to reproduce this issue using the following env.
could you give more inputs ?

```
./terraform -version
Terraform v0.14.2
+ provider registry.terraform.io/ovh/ovh v0.10.0
cat main.tf
variable service {
 type = string
}

provider "ovh" {
  endpoint           = "ovh-eu"
}

data ovh_cloud_project_regions regions {
   service_name = var.service
}

output value { 
value = data.ovh_cloud_project_regions.regions.names
}

 ./terraform init
...
 ./terraform apply
```

everything seems ok on my side

**Comment by laurentgrangeau** [comment]
Could this be related with my AK/SK/CK ?

**Comment by yanndegat** [comment]
i'm not sure what you're referring to with ak/sk/ck  ?

**Comment by laurentgrangeau** [comment]
I'm talking about my application_key, application_secret and consumer_key

**Comment by laurentgrangeau** [comment]
Ok, I've narrowed where the issue can be. It's when I'm using the `ovh_cloud_project_network_private` and when I'm trying to create a private network

**Comment by amstuta** [comment]
@laurentgrangeau I'm closing this issue because we can't reproduce the issue. Don't hesitate to re-open it and show us your configuration if you encounter the issue again.
