### ISSUE TITLE
Plans to support Private Databases

### ISSUE THREAD

**Issue by rhabbachi** [ovh/terraform-provider-ovh#190]
It would be useful to be able to create or affect manually created OVHCloud private databases resources. Specifically the ability to update the IP Whitelist and Databases and Users.

Any plans to incorporate these type of resources in the future?

### Terraform Version
>= 0.15.0

### References
- API Dashboard / Link https://api.ovh.com/console/#/hosting/privateDatabase

**Comment by amstuta** [comment]
@rhabbachi closing this issue since the resources have been created since then, see https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/hosting_privatedatabase

Don't hesitate to reopen it if the resource I linked isn't what you expected.
