### ISSUE TITLE
Feature request : kubernetes feature gates

### ISSUE THREAD

**Issue by madmatah** [ovh/terraform-provider-ovh#201]
Hi,

My request concerns the resource `ovh_cloud_project_kube`.
It would be great to be able to specify the list of feature gates to enable on the cluster.

FYI, my use case is the following : I am very interested in the [PodDeletionCost](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost) feature gate that will come with Kubernetes 1.21.
It is a great companion for HPA: it allows to make smarter decisions about which pods to terminate when scaling down a replicaset.

**Comment by scraly** [comment]
Hi @madmatah,
you can comment on the [Allow API server configuration change](https://github.com/ovh/public-cloud-roadmap/issues/70) request on our public cloud roadmap github with your need and precise that you want to for terraform provider only.

Thanks :)

**Comment by amstuta** [comment]
Closing this issue, issue should be resolved by the roadmap link shared above. Don't hesitate to re-open an issue if there are still uncovered features.
