### ISSUE TITLE
Feature Request: support for ip firewall modes, rules and mitigation options

### ISSUE THREAD

**Issue by skept1c** [ovh/terraform-provider-ovh#216]
Hi there,

Been configuring firewall rules for 30+ ip addresses via api yesterday and it was quite inconvenient; can`t even imagine how slow it would be if I had to do the same using manager ui.

Would be nice if the module gets firewall and mitigation configuration support.

**Comment by sergeyberezansky** [comment]
+1

**Comment by acejam** [comment]
+1

**Comment by hutm** [comment]
+1

**Comment by mario-purestake** [comment]
+1

**Comment by 131** [comment]
+1

**Comment by amstuta** [comment]
Resources `ovh_ip_firewall`, `ovh_ip_firewall_rule` and `ovh_ip_mitigation` have been added, don't hesitate to open another issue if you need other resources.
