### ISSUE TITLE
FEATURE ovh_cloud_project_kube restricted_ips

### ISSUE THREAD

**Issue by melck** [ovh/terraform-provider-ovh#240]
Hi,

I want to configure restricted ips on api-server Kubernetes services. Could you provide a optional parameter with a list to setup that ?

### Terraform Version
All

### Affected Resource(s)
- ovh_cloud_project_kube

**Comment by scraly** [comment]
Hi @melck ,
this feature of IP restrictions on a Kubernetes cluster will be added in the next release :)

**Comment by scraly** [comment]
The new [0.19.*](https://registry.terraform.io/providers/ovh/ovh/0.19.1) release includes this feature :)
