### ISSUE TITLE
Ability to replace domain zone record when it's the same type

### ISSUE THREAD

**Issue by folfix** [ovh/terraform-provider-ovh#251]
Hi!
I use **ovh_domain_zone_record** resource and I'd appreciate the option to override DNS record. Currently ovh_domain_zone_record's default behavior is to create new DNS record every time.
Proposed solution is to introduce an argument (i.e. override) which will consider zone, subdomain and fieldtype and if there is already such record, it will just override (update) target.

Thanks for your effort!

**Comment by amstuta** [comment]
Hey @folfix, I'm not sure this solution makes sense from a Terraform pov, I think a possible workflow is to import the existing record and then update it's configuration in your `.tf` file. What do you think ?

**Comment by amstuta** [comment]
Closing this issue since it's quite old. Don't hesitate to reopen it if still needed.
