### ISSUE TITLE
Feature Request: ovh_cloud_project_kube update_policy argument

### ISSUE THREAD

**Issue by vsychov** [ovh/terraform-provider-ovh#265]
Hi there,

For now not possible to change [update_policy](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_kube#update_policy) for cluster from terraform, it would be nice to have this as argument.

**Comment by matprig** [comment]
hello,

i have made a PR containing also this fix https://github.com/ovh/terraform-provider-ovh/pull/274

best,

**Comment by scraly** [comment]
The new [0.19.*](https://registry.terraform.io/providers/ovh/ovh/0.19.1) release includes this feature :)
