### ISSUE TITLE
Feature request: clouddb / postgresql database 

### ISSUE THREAD

**Issue by arthurzenika** [ovh/terraform-provider-ovh#268]
OVHCloud product : https://www.ovhcloud.com/en/public-cloud/postgresql/

On roadmap: https://github.com/ovh/public-cloud-roadmap/issues/124 there is discussion about a terraform way to manage the postgresql clusters,  databases, users, etc. 

The roadmap also has this ticket : https://github.com/ovh/public-cloud-roadmap/issues/137 that is related to this feature request. 

Scope : 

* manage databases on an existing cluster
* manage users 
* (less priority) manage clusters

**Comment by BellionBastien** [comment]
Hi there,
We are currently working on it, we've made a first PR to manage database clusters: https://github.com/ovh/terraform-provider-ovh/pull/269

We will work in the coming weeks on IP restriction and users for all db engines.

**Comment by scraly** [comment]
Hi @arthurzenika,
this feature will be added in. the next release 🙂

**Comment by scraly** [comment]
The new [0.19.*](https://registry.terraform.io/providers/ovh/ovh/0.19.1) release includes this feature :)
