### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by opsinstech** [ovh/terraform-provider-ovh#271]
Hello,

I have an issue using the ovh provider for managing DNS zones.

We still have some DNS records managed by hand on our zone. Some of them have been modified, but not the ones managed by terraform.

We got a SegFault from the plugin in those cases.

### Terraform Version
Terraform v1.2.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/ovh/ovh v0.16.0

### Affected Resource(s)
ovh_domain_zone_record.app_dns_records[0]
ovh_domain_zone_record.app_dns_records[1]
ovh_domain_zone_record.app_dns_records[2]
ovh_domain_zone_record.app_dns_records[3]
ovh_domain_zone_record.app_dns_records[4]
ovh_domain_zone_record.app_dns_records[5]
ovh_domain_zone_record.app_dns_records[6]
ovh_domain_zone_record.app_dns_records[7]
ovh_domain_zone_record.app_dns_records[8]
ovh_domain_zone_record.app_dns_records[9]
ovh_domain_zone_record.app_dns_records[10]
ovh_domain_zone_record.app_dns_records[11]
ovh_domain_zone_record.app_dns_records[12]

### Terraform Configuration Files
```hcl
locals {
  # flatten ensures that this local value is a flat list of objects, rather
  # than a list of lists of objects.
  records = flatten([
    for env in var.envs : [
      for service in var.services : "${env == "recipe" ? "pre" : env}-${service}"
    ]
  ])
}

resource "ovh_domain_zone_record" "app_dns_records" {
  count = length(local.records)

  zone      = "redacted"
  subdomain = local.records[count.index]
  fieldtype = "A"
  ttl       = "60"
  target    = azurerm_public_ip.rp_pub_ip.ip_address
}

resource "ovh_domain_zone_record" "tools_dns_records" {
  count = length(var.tools)

  zone      = "eracoel.io"
  subdomain = "${var.tools[count.index]}-${var.infra}-${var.env}"
  fieldtype = "A"
  ttl       = "60"
  target    = azurerm_public_ip.rp_pub_ip.ip_address
}

```

### Debug Output
[Crash logs](https://gist.github.com/opsinstech/30e85bf9e3f7879ee5af8e0d0981d361)

### Expected Behavior
a basic terraform plan

### Actual Behavior
The plan took a long time to just crash.

### Steps to Reproduce
- Create a DNS zone in ovh.com
- Create records with terraform
- Create records by hand
- Try to plan again with terraform

**Comment by yomovh** [comment]
Sorry for the long time to come back to you.
I have not been able to reproduce it with current version (0.26)

Are you able to reproduce it with this version @antoineozenne  @opsinstech  ?

**Comment by yomovh** [comment]
Closing issue, please reopen if needed.
