### ISSUE TITLE
LoadBalancer / Frontend : default_ssl_id defaults to 0 instead of null, producing error 500 in OVH API.

### ISSUE THREAD

**Issue by qmartouzet** [ovh/terraform-provider-ovh#297]
### Terraform Version

- Terraform v1.2.8
- terraform-provider-ovh v0.19.1

### Affected Resource(s)

- ovh_iploadbalancing_http_frontend
- ovh_iploadbalancing_tcp_frontend

### Terraform Configuration Files
```hcl

terraform {
  required_version = ">= 1.2.8"
  required_providers {
    ovh = {
      source  = "ovh/ovh"
      version = ">= 0.19.1"
    }
  }
}

resource "ovh_iploadbalancing_tcp_frontend" "tcp-frontend" {
  service_name   = "loadbalancer-XXXX"
  display_name   = "ingress-443-tcp-sbg"
  zone           = "sbg"
  port           = "443"
  default_ssl_id = null

resource "ovh_iploadbalancing_http_frontend" "http-frontend" {
  service_name   = "loadbalancer-XXXX"
  display_name   = "ingress-80-http-sbg"
  zone           = "sbg"
  port           = "80"
  default_ssl_id = null
}

```

### Debug Output
```
│ Error: calling /ipLoadbalancing/loadbalancer-XXXX/http/frontend/999999:
│ 	 Error 500: "Internal server error"
│ 
│   with ovh_iploadbalancing_tcp_frontend.tcp-frontend,
│   on ./main.tf line 71, in resource "ovh_iploadbalancing_tcp_frontend" "tcp-frontend":
│   71: resource "ovh_iploadbalancing_tcp_frontend" "tcp-frontend" {


│ Error: calling /ipLoadbalancing/loadbalancer-XXXX/tcp/frontend/999999:
│ 	 Error 500: "Internal server error"
│ 
│   with ovh_iploadbalancing_http_frontend.http-frontend,
│   on ./main.tf line 71, in resource "ovh_iploadbalancing_http_frontend" "http-frontend":
│   71: resource "ovh_iploadbalancing_http_frontend" "http-frontend" {
```

With full debug enabled, I can see the actual request made to OVH backend : 

```
---[ REQUEST ]---------------------------------------
PUT /1.0/ipLoadbalancing/loadbalancer-b6b87cea7746e440d3e52453e43fc2a2/tcp/frontend/158313 HTTP/1.1
Host: eu.api.ovh.com
User-Agent: Go-http-client/1.1
Content-Length: 152
Accept: application/json
Content-Type: application/json;charset=utf-8
X-Ovh-Application: XXXXXXXXXXXX
X-Ovh-Consumer: XXXXXXXXXXXX
X-Ovh-Signature: $1$XXXXXXXXXXXXXX
X-Ovh-Timestamp: 9999999999
Accept-Encoding: gzip

{
 "port": "8443",
 "zone": "sbg",
 "allowedSource": [],
 "dedicatedIpfo": [],
 "defaultFarmId": 209318,
 "defaultSslId": 0,
 "disabled": false,
 "ssl": false,
 "displayName": ""
}
```

### Expected Behavior

There is 2 problems as I far I can understand :
- OVH API should return a 404 when `defaultSslId` is set to `0`, as it does when `defaultSslId` is set to `-1` ou any non-existent SSL ID => I think I should open a support ticket elsewere. Can anyone direct me to the right ticketing platform ?
- OVH terraform provider should not set `default_ssl_id` to a default `0` value when value `null` is explicitly specified. I suggest it should default to `null`.

### Actual Behavior

1. `default_ssl_id` is set to `0` by default, even if I don't want to use a SSL cert. 
2. API produces a HTTP 500 error. 
3. Frontend is not created...

### Steps to Reproduce

1. `terraform apply`

### More info

My use-case is to load-balance some TCP connections. LB is not doing any SSL termination so I won't have any SSL cert for now.

**Comment by juluanb** [comment]
Hello, I am also interested in a resolution of this issue (unfortunately, I'm not able to propose any correction by myself, sorry). 
Thanks in advance to anyone that can help!

**Comment by qmartouzet** [comment]
Issue fixed by https://github.com/ovh/terraform-provider-ovh/pull/302.

Thanks.
