### ISSUE TITLE
OpenSearch and ACL on avnadmin built-in account

### ISSUE THREAD

**Issue by albundy83** [ovh/terraform-provider-ovh#308]
Hello,

I use terraform `v1.2.9` with OVH provider `v0.21.0`

Updating ACL on built-in account avnadmin is not possible as it first try to create it.
Here the output :
`Error: calling Post /cloud/project/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/database/opensearch/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/user with params &{Acls:[{Pattern:_* Permission:admin} {Pattern:* Permission:admin}] Name:avnadmin}:
│        "Error 409: \"Bad Request\""`

And the full debug message to explain the 409 error code:
```json
{
 "class": "Client::Conflict::BadRequest",
 "message": "Bad Request",
 "details": {
  "message": "Service user 'avnadmin' already exists"
 }
}
```
I have try to same call using OVH api and of course same output.
We should be able to use PUT methode instead of POST...
But how can I achieve that please ?

**Comment by albundy83** [comment]
Just try with this new great release so perfectly indented `v0.22.0` but unfortunatelly, the issue with the built-in account `avnadmin` is still present...
Don't you have a trick for me please ?

**Comment by lpatte** [comment]
Hi,
`avnadmin` is create automatically to do only admin work, and not to work on data.
We advise to create another user with needed ACLs.

If you really want to use `avnadmin` with ACLs, you can use `terraform import` to import `avnadmin` in your terraform state. Update the imported resource with needed ACLs to update `avnadmin` ACLs.

```bash
# Deploy opensearch service
terraform apply -auto-approve
```
```hcl
# Add in your terraform file
resource "ovh_cloud_project_database_opensearch_user" "advadmin" {
  # (resource arguments)
}
```
```bash
# Import advadmin user 
terraform import ovh_cloud_project_database_opensearch_user.advadmin <service_name>/<cluster_id>/<user_id>
```
```hcl
# Align your terraform file with the state
resource "ovh_cloud_project_database_opensearch_user" "avnadmin" {
  service_name = <service_name>
  cluster_id = <cluster_id>
  name = "avnadmin"
}
```
Finally update the resource with needed ACLs then apply to update it

**Comment by albundy83** [comment]
Ah ok, I understand, thanks a lot for the trick :)
