### ISSUE TITLE
Resources for object storages with S3-API

### ISSUE THREAD

**Issue by maylukas** [ovh/terraform-provider-ovh#329]
It is currently impossible to create the new Object Storage variants with an S3-API through Terraform
![image](https://user-images.githubusercontent.com/7526728/196765347-14a28e88-05ba-4295-841d-6d13389a5a8a.png)

It should be possible to create resources that can be created through the UI with Terraform

**Comment by yomovh** [comment]
Hi @maylukas,

Thanks for the feature request.

Currently our suggestion is to use [hashicorp aws provider ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)
with the following configuration (access_key and secret_key are ovh tf ressource as you can see) :

> 
> provider "aws" {
>     region      = var.region
>     access_key  = ovh_cloud_project_user_s3_credential.admin_cred.access_key_id
>     secret_key  = ovh_cloud_project_user_s3_credential.admin_cred.secret_access_key
>     skip_credentials_validation = true
>     skip_requesting_account_id  = true
>     skip_region_validation = true
>     endpoints {
>         s3 = var.s3_endpoint
>     }
> }

**Comment by sambonbonne** [comment]
Hello @yomovh,

I tried using your configuration:

```hcl
provider "aws" {
  region = "gra"

  access_key = ovh_cloud_project_user_s3_credential.backups_user_credentials.access_key_id
  secret_key = ovh_cloud_project_user_s3_credential.backups_user_credentials.secret_access_key

  skip_credentials_validation = true
  skip_requesting_account_id  = true
  skip_region_validation      = true

  endpoints {
    s3 = "https://s3.gra.io.cloud.ovh.net"
  }
}
```

But when running `terraform plan` I get this error:

```
╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 21, in provider "aws":
│   21: provider "aws" {
│
╵
```

I tried adding `skip_metadata_api_check = true` in the AWS provider but it just change the error to:

```
╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, access disabled to EC2 IMDS via client option, or "AWS_EC2_METADATA_DISABLED" environment variable
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 21, in provider "aws":
│   21: provider "aws" {
│
╵
```

Do I miss anything, like another `endpoints` to set?

Just for you know, I use the following versions:

```
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.48.0
+ provider registry.terraform.io/ovh/ovh v0.25.0
```

**Comment by yomovh** [comment]
@sambonbonne : I will publish to github my (humble) bucket  plan so that you can try it yourself : with my test, one `apply` was enough ;-)

**Comment by yomovh** [comment]
@sambonbonne : https://github.com/ovh/public-cloud-examples/pull/17

**Comment by sambonbonne** [comment]
@yomovh by cloning your example and running it with `terraform plan` and `terraform apply`, I still get the error. I don't understand how it can work, did I miss something? 

FYI I set the `OVH_APPLICATION_KEY`, `OVH_APPLICATION_SECRET` and `OVH_CONSUMER_KEY` environment variables before running Terraform commands.

**Comment by yomovh** [comment]
@sambonbonne : you are right, I missed something : the fact that the AWS provider needs a key & secret at init time (and on my configuration it was getting the AWS CLI variables that were stored in `.aws`directory.)
This limitation is described in this long lasting terraform [issue](https://github.com/hashicorp/terraform/issues/2430)

The workaround I found was to set environment variable `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` to dummy values so that the AWS provider initialize successfully and then the values are overriden by the terraform script. 

Another work around is described in this issue [comment](https://github.com/hashicorp/terraform/issues/2430#issuecomment-195430847). It consists in using 2 modules and use the `-target` when launching terraform to define the order (in our case, first ovh provider resources then AWS ones)

**Comment by yomovh** [comment]
@sambonbonne @maylukas : we will be releasing a tutorial on S3 provisioning with terraform. They will be based on my examples : https://github.com/yomovh/tf-at-ovhcloud

**Comment by bcouetil** [comment]
Thank you for your example, it worked for me too.

Really simple, I did not have to navigate around dozen files 🙏

**Comment by loliee** [comment]
This doc [Object Storage - S3 Compliancy](https://docs.ovh.com/ie/en/storage/object-storage/s3/s3-compliancy/) is also useful to guess which resources are supported !

@yomovh Can we build safetly around this aws provider ? No plan to integrate this is in the OVH provider right ?

**Comment by yomovh** [comment]
@loliee  : our current strategy is to support S3 API so that all the tools around S3 can be used with OVHCloud S3 implementation. Hashicorp AWS provider is part of those tools. So no plan to integrate it into OVH provider soon.

**Comment by loliee** [comment]
This provider is huge with a lot of resources and I'm afraid that it will be difficult to know what it is really supported by OVH.
I really hope you will write a complete and accurate documentation about S3 support with this provider and not a simple disclaimer about using it.
Object Storage is a fundamental piece of cloud computing and managing it with a IAC tool like terraform is crucial. I think many of your customers (like us) are waiting for this. 
Until here object storage at OVH was for me a real pain point, with your new object storage solution I can see the light a the end of the tunnel ;)

**Comment by yomovh** [comment]
We released a guide on the official documentation site that links the sample repo mentionned above https://docs.ovh.com/gb/en/storage/object-storage/s3/manage-s3-bucket-with-terraform/
Closing the issue
