### ISSUE TITLE
Workflow/Backup

### ISSUE THREAD

**Issue by Safranil** [ovh/terraform-provider-ovh#330]
Hi,

Is it possible to add the ability to manage instance backup (Workflow Management) for OVH Public Cloud with this Terraform Module?

That will be great has this task is done manually and would be done easily with Terraform.

**Comment by yomovh** [comment]
Shipped 0.28

**Comment by tbukic** [comment]
Hey @yomovh , I think the [documentation page](https://help.ovhcloud.com/csm/en-terraform-at-ovhcloud?id=kb_article_view&sysparm_article=KB0054775#containers-orchestration) needs to be updated to reflect this update.
