### ISSUE TITLE
Support for specifying database "advanced configuration"

### ISSUE THREAD

**Issue by d0x2f** [ovh/terraform-provider-ovh#335]
Hello,

As a feature request, I'd like the ability to specify the same "advanced configuration" options available in the web interface via terraform.

For me specifically, I need to configure the sql_mode & sql_require_primary_key settings of a mysql database.
I'm looking into doing this with a script via the rest api for now.

Thanks!

### Terraform Version
$ terraform -v
Terraform v1.3.4
on linux_amd64

registry.terraform.io/ovh/ovh 0.22.0

**Comment by lpatte** [comment]
Hello,

Thanks for the request, that a MUST for sure. 
The request is now tracked on our side and should be implement for a future release.

**Comment by yomovh** [comment]
Shipped in 0.28.0, closing the issue

**Comment by biapar** [comment]
Don't work. I've MYSQL Public cloud and I've this sql mode:
{
  "mysql.sql_mode": "ANSI,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_ALL_TABLES",
  "mysql.sql_require_primary_key": "false"
}
but in MYSQL there is:
'REAL_AS_FLOAT,PIPES_AS_CONCAT,ANSI_QUOTES,IGNORE_SPACE,ONLY_FULL_GROUP_BY,ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
