### ISSUE TITLE
Please add a resource for cloud archives

### ISSUE THREAD

**Issue by khaledavarteq** [ovh/terraform-provider-ovh#343]
Hello,

it's possible to create object storage containers using the OpenStack resource [objectstorage_container_v1](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/objectstorage_container_v1). However, a cloud archive container, which uses OpenStack Swift containers a backend, cannot be created using either the OpenStack or OVH modules. Therefore, I'd like to ask you to add a resource type for cloud archives. In addition, it would be great if cloud archives could have ACLs set on them like with the object storage containers.

**Comment by yomovh** [comment]
Hi @khaledavarteq 

You can create a cloud archives just by using the  [objectstorage_container_v1](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/objectstorage_container_v1) and setting the storage policy to "PCA".

This newly created [page](https://docs.ovh.com/gb/en/api/terraform-at-ovhcloud/#storage-and-backup) may help you to find the data source from a *Manager* concept.

**Comment by yomovh** [comment]
Fixed in the documentation
