### ISSUE TITLE
How to setup a secured Kubernetes cluster with Terraform

### ISSUE THREAD

**Issue by bcouetil** [ovh/terraform-provider-ovh#359]
Hello 😊

I'm trying to deploy a kubernetes cluster with private nodes.

I'm trying to automate at maximum with Terraform.

I'm having a hard time finding on internet what to configure in `private_network_configuration`, especially in `default_vrack_gateway`.

Should I do half Terraform, half commands from the detailed post [Using a custom gateway on an OVHcloud Managed Kubernetes cluster](https://docs.ovh.com/gb/en/kubernetes/vrack-k8s-custom-gateway/#link-the-router-to-the-external-provider-network) ?

Alternatively, with Terraform, is it possible to deploy a cluster with public nodes (the default behavior) and have it basically secured (outbound traffic open from nodes, inbound traffic blocked except ingress controller load balancer and masters) ?

I don't mind disabling autoscaling to achieve that.

Thanks for any input 🙏

**Comment by yomovh** [comment]
Thanks for your issue. 
You should be able to do (almost) everything with terraform. However, as described in this documentation [page](https://docs.ovh.com/gb/en/api/terraform-at-ovhcloud/), you will need to use at least 2 providers (ovh, openstack) and maybe kubernetes one. 

You can have a look at [that project](https://github.com/ovh/public-cloud-examples) that contains multiple examples. In particular your need seems to be close to this [example](https://github.com/ovh/public-cloud-examples/tree/main/examples/03) on a managed Kubernetes cluster that is connected to a managed MySQL database, and everything inside a private network courtesy of @raclepoulpe

**Comment by bcouetil** [comment]
Thank you very much for your quick and detailed response 🙏 

I'll dig into that.

**Comment by raclepoulpe** [comment]
Hello @bcouetil , @yomovh 's response is perfect.
I'm going to rewrite soon this tutorial, because we provide, since november, L3 routers with private networks, that are Terraform manageable!
So until rewrited, go an find useful examples on our https://github.com/ovh/public-cloud-examples repository, and especially the n°3 for your need 👍

**Comment by yomovh** [comment]
Closing issue as there is nothing to fix.

**Comment by bcouetil** [comment]
Hello @yomovh, @raclepoulpe ☺️

Thank you for the inputs, I've been able to install a stack very similar to the one pointed out on @raclepoulpe repo.

But my worker nodes still have a public IP each (and a DDOS attack attempt has been experienced yesterday, without consequence).

Did I miss something ?

```hcl
data "openstack_networking_network_v2" "ext_net" {
  name   = "Ext-Net"
  region = var.region
}

resource "openstack_networking_network_v2" "private_network" {
  name           = "${terraform.workspace}-private-network"
  region         = var.region
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "subnet" {
  network_id      = openstack_networking_network_v2.private_network.id
  region          = var.region
  name            = "${terraform.workspace}-subnet"
  cidr            = "192.168.12.0/24"
  enable_dhcp     = true
  no_gateway      = false
  dns_nameservers = ["1.1.1.1", "1.0.0.1"]

  allocation_pool {
    start = "192.168.12.100"
    end   = "192.168.12.254"
  }
}

resource "openstack_networking_router_v2" "router" {
  region              = var.region
  name                = "${terraform.workspace}-router"
  admin_state_up      = true
  external_network_id = data.openstack_networking_network_v2.ext_net.id
}

resource "openstack_networking_router_interface_v2" "router_interface" {
  router_id = openstack_networking_router_v2.router.id
  region    = var.region
  subnet_id = openstack_networking_subnet_v2.subnet.id
}

resource "ovh_cloud_project_kube" "cluster" {
  service_name = var.project_id[terraform.workspace]
  name         = "${terraform.workspace}-cluster"
  region       = var.region

  private_network_id = openstack_networking_network_v2.private_network.id

  private_network_configuration {
    default_vrack_gateway              = "192.168.12.1"
    private_network_routing_as_default = true
  }
}

resource "ovh_cloud_project_kube_nodepool" "node_pool" {
  service_name = var.project_id[terraform.workspace]
  name         = "${terraform.workspace}-pool"
  kube_id      = ovh_cloud_project_kube.cluster.id
  flavor_name  = "b2-15"
  # TODO : configure using https://docs.ovh.com/us/en/kubernetes/configuring-cluster-autoscaler/, not available in terraform
  # autoscale = true # default false
  desired_nodes = 3
  max_nodes     = 3
  min_nodes     = 3
}

resource "local_sensitive_file" "kubeconfig" {
  content         = ovh_cloud_project_kube.cluster.kubeconfig
  filename        = "${terraform.workspace}.kubeconfig"
  file_permission = "0644"

  depends_on = [ovh_cloud_project_kube.cluster, ovh_cloud_project_kube_nodepool.node_pool]
}
```

**Comment by raclepoulpe** [comment]
Hi [bcouetil](https://github.com/bcouetil)!
This public IPs now are only used for admin tasks
This is something we are working on, bit for now, don't worry, your cluster is safe :)

**Comment by bcouetil** [comment]
Ok, it's all good then, thanks 🙏

**Comment by bcouetil** [comment]
For anyone coming here to find a complete response to the original question, I've written a blog post on the subject : https://dev.to/zenika/how-to-deploy-a-secured-ovh-managed-kubernetes-cluster-using-terraform-in-2023-17o7
