### ISSUE TITLE
Scale kubernetes pool to 0 not work using Terraform

### ISSUE THREAD

**Issue by MircoT** [ovh/terraform-provider-ovh#370]
Hi,

I had problem to scale to zero a Kubernetes pool using Terraform. The change was not applied, I had to do it manually from the web panel.

### Terraform Version
`Terraform v1.3.7`

### Affected Resource(s)
- `ovh_cloud_project_kube_nodepool`

### Terraform Configuration Files
```hcl
resource "ovh_cloud_project_kube_nodepool" "node_pool" {
  service_name  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  kube_id       = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  name          = "my-pool-1" //Warning: "_" char is not allowed!
  flavor_name   = "b2-7"
  desired_nodes = 1 // change this from 1 to 0 and then apply
  max_nodes     = 3
  min_nodes     = 0
}
```

### Debug Output
Nothing so see there, for Terraform the changes were applied successfully.

### Panic Output
Nothing so see there, for Terraform the changes were applied successfully.

### Expected Behavior
The scale to 0 of the node pool should be the final result.

### Actual Behavior
The pool size remains to 1.

### Steps to Reproduce
Just create a simple pool with 1 node and then scale the number of desired nodes o 0 and apply the changes.

### References
Didn't see anything as an opened issue.

**Comment by matprig** [comment]
Hello,

Thanks, indeed, this is an issue, 0 is badly considered as nil which is not serialize and by the way...

we are on it

best,
