### ISSUE TITLE
Change to monthly billing using Terraform destroys the pool

### ISSUE THREAD

**Issue by MircoT** [ovh/terraform-provider-ovh#371]
Hi,

I don't know if it is exactly an issue, but passing from hourly billing to monthly destroys the whole pool.

### Terraform Version
`Terraform v1.3.7`

### Affected Resource(s)
- `ovh_cloud_project_kube_nodepool`

### Terraform Configuration Files
```hcl
resource "ovh_cloud_project_kube_nodepool" "node_pool" {
  service_name  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  kube_id       = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  name          = "my-pool-1" //Warning: "_" char is not allowed!
  flavor_name   = "b2-7"
  desired_nodes = 3
  max_nodes     = 3
  min_nodes     = 3
  monthly_billed = false
}
```

### Expected Behavior
Upgrade the billing without destroying the pool.

### Actual Behavior
The pool is completely wipe out and recreated.

### Steps to Reproduce
Change the `monthly_billing` from `false` to `true` and then apply.

**Comment by matprig** [comment]
Hello,
As describe in the documentation https://docs.ovh.com/ie/en/kubernetes/node-pools-crd/

_flavor, monthlyBilled and antiAffinity are not editable_

by the way terraform provider implementation respects that, if modified then the resource is recreated(destroy and add new resource)

best,

**Comment by mhurtrel** [comment]
Note that we will propose next year a mich more flexible way to commit on spendings in exchange for rebates, without adherence to specific resources, avoiding these limitations : https://github.com/ovh/public-cloud-roadmap/issues/67
