### ISSUE TITLE
How to define the VLAN ID when creating a private network ?

### ISSUE THREAD

**Issue by bcouetil** [ovh/terraform-provider-ovh#382]
Hello,

How do I define the VLAN ID using openstack_networking_network_v2, like I can do in OVH console ?

Thanks.

### Affected Resource(s)

openstack_networking_network_v2 and maybe others

### Expected Behavior

Ability to define the VLAN ID

**Comment by al26p** [comment]
Hi ! 

I use the following snippet to instantiate a Vrack network using a custom VLAN ID. 

I hope it answers your question and I wish you a great day !

```
resource "openstack_networking_network_v2" "my_network" {
  name = "my_42 vrack_network"
  value_specs = {
    "provider:network_type"    = "vrack"
    "provider:segmentation_id" = 42
  }
}
```

**Comment by yomovh** [comment]
Thanbks @al26p. I will update the documentation accordingly and close the issue when the docs is available.

**Comment by bcouetil** [comment]
Many thanks @al26p, I will try this asap 🙏

**Comment by yomovh** [comment]
Documentation is published on this [page](https://docs.ovh.com/ie/en/publiccloud/network-services/public-cloud-vrack/#creating-a-private-network-with-terraform) 

Closing the issue
