### ISSUE TITLE
Unable to complete operation on subnet during Terraform destroy

### ISSUE THREAD

**Issue by chris-cynation** [ovh/terraform-provider-ovh#384]
Hi,

I'm running Terraform 1.38 that has created kubernetes cluster on a private network and subnet.

However it is consistently failing at the final resources.

The error message is 
Error: calling DELETE /cloud/project/id/network/private/netId/subnet/subnetId:
"Unable to complete operation on subnet subnetId: One or more ports have an IP allocation from this subnet."

terraform -v
Terraform v1.3.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/ovh/ovh v0.27.0

steps to produce
1. terraform apply create kubernetes cluster on private network and subnet.
2. terraform destroy.

I beleve the ovh provider has a timing issue.  It should probably retry with expotential back-off or is returning before the kubernetes cluster is actually deleted.

**Comment by yomovh** [comment]
Hello,

It is difficult to help you without the logs. However, if this is a timeout issue, you can now specify the timeout (see [nodepool timeout configuration](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_kube_nodepool#timeouts) for instance

**Comment by chris-cynation** [comment]
Hey,

It's the next resource after node pool that errors.   


The defintion is

`resource "ovh_cloud_project_network_private_subnet" "networksubnet" {
  service_name = ovh_cloud_project_network_private.network.service_name
  network_id   = ovh_cloud_project_network_private.network.id

  # whatever region, for test purpose
  region     = var.region
  start      = var.private_kub_subnet_start
  end        = var.private_kub_subnet_end
  network    = var.private_kub_subnet_cidr
  dhcp       = true
  no_gateway = false

  depends_on   = [ovh_cloud_project_network_private.network]
}`

The log has this line just above it
module.managedservices.ovh_cloud_project_kube_nodepool.node_pool: Destruction complete after 1m7s

**Comment by chris-cynation** [comment]
Discovered the issue.

The kube cluster wasn't correctly included in the dependacy for the subnet as the kube resopurce takes a private_network_id attribute.
