### ISSUE TITLE
postgreSQL 15 - wrong user privilege upon db creation

### ISSUE THREAD

**Issue by khaledavarteq** [ovh/terraform-provider-ovh#391]
### Describe the bug
When I used the resources `ovh_cloud_project_database` and `ovh_cloud_project_database_postgresql_user` to set up a new PostgreSQL instance of version 15.x, the user was not allowed to create new database tables. The same code works for PostgreSQL 14.x instances. When trying to create a table, I got the following error:

```sql
"defaultdb=> CREATE TABLE Persons (PersonID int);
ERROR:  permission denied for schema public
LINE 1: CREATE TABLE Persons (PersonID int);"
```

According to an OVH support engineer this is an issue with PostgreSQL 15.x: [PostgreSQL 15 also revokes the CREATE permission from all users](https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS). The new user's access privileges:

```psql (15.2 (Debian 15.2-1.pgdg110+1), server 15.1)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.

defaultdb=> \dn+
                                       List of schemas
  Name  |       Owner       |           Access privileges            |      Description       
--------+-------------------+----------------------------------------+------------------------
 public | pg_database_owner | pg_database_owner=UC/pg_database_owner+| standard public schema
        |                   | =U/pg_database_owner                   | 
(1 row)
```

### Terraform Version

Terraform v1.2.9

### OVH Terraform Provider Version

+ provider registry.terraform.io/ovh/ovh v0.27.0

### Affected Resource(s)

- ovh_cloud_project_database
- ovh_cloud_project_database_postgresql_user

### Expected Behavior

A PostgreSQL 15.x instance should have been created with a user appropriate access privileges.

### Actual Behavior

The PostgreSQL 15.x instance was created as well as the user but the user does not have appropriate access privileges.

### Steps to Reproduce

1. Create a PSQL 15.x instance
2. Create a user with access to the new instance
3. Try to create a table in the `defaultdb`

**Comment by yomovh** [comment]
thanks for your issue, I have redirected it to the product team.

**Comment by thild42** [comment]
Just a quick acknowledgement to let you know that the dev is on this issue.

**Comment by lpatte** [comment]
Like OVH support said, this is the normal behavior of a freshly created PostgreSQL 15.
It was a usage pattern already recommended, and PostgreSQL 15 support it by default.
At this time, this Terraform provider create a PostgreSQL user with default privilege, so this is the expected behavior here.

Work around:
Updated Database does not revoke this privilege by default. A PostgreSQL 14 upgraded to PostgreSQL 15 keep the possibility for all users to create in Public schema.
