### ISSUE TITLE
[BUG] Cannot order a cloud project when default payment mean is bank account

### ISSUE THREAD

**Issue by xtof-osd** [ovh/terraform-provider-ovh#405]
### Describe the bug

Trying to order an OVH Cloud project (resource "ovh_cloud_project" ) using provider.
My account has a default payment mean set, which is bank account

### Terraform Version

Terraform v1.3.7
on linux_amd64

### OVH Terraform Provider Version

+ provider registry.terraform.io/ovh/ovh v0.29.0
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.48.0

### Affected Resource(s)

ovh_cloud_project
### Terraform Configuration Files

```hcl
data "ovh_order_cart" "terraform_managed_cart" {
  ovh_subsidiary = "fr"
  description    = "Terraform managed cart"
}
data "ovh_order_cart_product_plan" "plan_project_t4" {
  cart_id        = data.ovh_order_cart.terraform_managed_cart.id
  price_capacity = "renew"
  product        = "cloud"
  plan_code      = "project.2018"
}

resource "ovh_cloud_project" "tekfor" {
  description    = "tekfor"
  ovh_subsidiary = data.ovh_order_cart.terraform_managed_cart.ovh_subsidiary

  plan {
    duration     = data.ovh_order_cart_product_plan.plan_project_t4.selected_price.0.duration
    plan_code    = data.ovh_order_cart_product_plan.plan_project_t4.plan_code
    pricing_mode = data.ovh_order_cart_product_plan.plan_project_t4.selected_price.0.pricing_mode

  }
}

```

### Debug Output
n.a.

### Panic Output
n.a.

### Expected Behavior

create project 

### Actual Behavior

command created (visible in OVH control panel) but terraform fails:
```
ovh_cloud_project.tekfor: Creating...
╷
│ Error: Could not order cloud project: "calling Post /me/order/188930148/pay:\n\t \"HTTP Error 403: \\\"This order can't be paid with 'bankAccount'\\\"\""
│ 
│   with ovh_cloud_project.tekfor,
│   on 03_ovh_cloud_project.tf line 10, in resource "ovh_cloud_project" "tekfor":
│   10: resource "ovh_cloud_project" "tekfor" {
│ 
╵
`è `

### Steps to Reproduce

`terraform apply`

### References
n.a.

### Additional context
n.a.

**Comment by yomovh** [comment]
Thanks for your issue.  Investigating.

**Comment by yomovh** [comment]
It seems that this issue was not seen in our tests because we were using  `SEPA_DIRECT_DEBIT` and you are using `BANK_ACCOUNT`.
The difference between the 2 is that `BANK_ACCOUNT`is legacy.
I suppose that if you create a new payment mean will it will be created as a `SEPA_DIRECT_DEBIT` and ordering via terraform should be OK. 

Meanwhile we are investigating to fix the issue with the legacy payment.

**Comment by surprisingb** [comment]
After more than 6 months this is still an issue.
@yomovh any news?

**Comment by bbitarelle** [comment]
Hi,

I'm also facing this issue.
If I understand if I create another payment method, it should modify the legacy term with `SEPA_DIRECT_DEBIT` right ?

**Comment by yomovh** [comment]
Sorry for being so long to answer to you. 

Indeed, `BANK_ACCOUNT` is deprecated and shall be replaced by `SEPA_DIRECT_DEBIT` 
You can update this through the Web Control Panel (Manager) or through API.
