### ISSUE TITLE
Reset avnadmin password on creation of ovh_cloud_project_database / grafana

### ISSUE THREAD

**Issue by D3N14L** [ovh/terraform-provider-ovh#407]
### Description

On several dabase engines there is a pre-created avnadmin user. After the creation of the database the user has to reset the password of the avnadmin to be able to connect and use the database. However, this is breaking automation in certain cases.

For example: I want to create a `ovh_cloud_project_database` resource with the engine type `grafana`. After the resource is created I can not access the avnadmin users password with terraform to configure the grafana Terraform provider and start configuring Grafana with it. Instead I have to put the Grafana resources into a separate Terraform stack, manually reset the avnadmin users password and enter it to the second Terraform stack. This breaks the automation workflow with Terraform and adds manual steps.

##### Reset password on CREATE

To be able to use any resource with the avnadmin default user pre-created one has to reset the password directly after creation of the database resource. This could be automated in the existing resource by triggering a password reset in the CREATE operation of the provider and outputting the avnadmin users password as an resource attribute.

##### Use the same mechanism as for the postgres engine

For some database engines there is a solution for this implemented in https://github.com/ovh/terraform-provider-ovh/pull/360. The soultion is to create a database user resource with the name "avnadmin" and trigger the password reset via this resource.  

### Affected Resource(s) and/or Data Source(s)

* ovh_cloud_project_database
* maybe more depending on the management of the avnadmin user in the specifice engine type.

### Potential Terraform Configuration

The first proposal comes without changes to the exisitng terraform configuration. Just a new attribute has to be added to `ovh_cloud_project_database` to output the password. 

For the second proposal a resource could be added that looks similar to the `ovh_cloud_project_database_postgresql_user` resource:
```
resource "ovh_cloud_project_database_grafana_user" "avnadmin" {
  service_name   = ovh_cloud_project_database.db.service_name
  cluster_id     = ovh_cloud_project_database.db.id
  name           = "avnadmin"
  password_reset = var.reset_avnadmin_password
}
```

**Comment by biapar** [comment]
Avnadmin don't has SUPER privileges. Please add to it.

**Comment by yomovh** [comment]
@D3N14L : can you confirm that this feature is only for grafana ? For us, the avnadmin user password reset is already available for other engines. 

@biapar : can you be more specific please ?

**Comment by D3N14L** [comment]
@yomovh - this specific request is only for grafana, yes.

However, looking at what user could be created/managed with which Terraform object looked a bit "patchworky". Also there is no real documentation for the hardcoded "hack" in https://github.com/ovh/terraform-provider-ovh/pull/360 that makes it possible to manage the *existing* `avndamin` in several db-engines by creating a *new* Terraform resource for this user object. So a general rework and documentation of the DB user resources would be nice. But that should be done in a different ticket.
