### ISSUE TITLE
[Feature] implement /dedicated/server/{serviceName}/bringYourOwnImage 

### ISSUE THREAD

**Issue by netlinkz** [ovh/terraform-provider-ovh#409]
I couldn't see anywhere in the docs where you can trigger /dedicated/server/{serviceName}/bringYourOwnImage
Is it possible currently?

Also, is there a generic API function that can leverage the request signing functionality? I.e. Is there something like the terraform http provider just with request signing ability?

**Comment by yomovh** [comment]
Thanks for your issue. 

This is currently not implemented in the provider.  I put your request in the backlog and inform the product team. 

For generic request, I have not tried so may be ;-)

**Comment by Eclion** [comment]
Hello @netlinkz !
AFAIK, they are not implementing it because they will change the API. c.f. #450 & #434

**Comment by amstuta** [comment]
Closing this issue as the feature won't be implemented using route `/dedicated/server/{serviceName}/bringYourOwnImage` (see the issue and PR mentioned by @Eclion). It will directly be implemented in resource `ovh_dedicated_server_install_task` (currently in development).
