### ISSUE TITLE
 [Feature] IPLB udp frontend

### ISSUE THREAD

**Issue by XLordalX** [ovh/terraform-provider-ovh#415]
Is it possible to create a UDP loadbalancing frontend using this provider?

**Comment by yomovh** [comment]
Hello,

Unfortunately this is not yet implemented in the provider see [here](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/iploadbalancing)

**Comment by amstuta** [comment]
@XLordalX resource `ovh_iploadbalancing_udp_frontend` is now available
