### ISSUE TITLE
[DOCS] ovh_iploadbalancing_http_farm lacks documentation of import procedure

### ISSUE THREAD

**Issue by xtof-osd** [ovh/terraform-provider-ovh#429]
### Documentation link

https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/iploadbalancing_http_farm#import

### Description

There is no mention of the ability to import iploadbalancing_http_farm ressources, yet sourcecode a `resourceIpLoadbalancingHttpFarmImportState` that seems to enable import by id

**Comment by xtof-osd** [comment]
Now that we make a more intensive usage of Terraform provider at Tekfor, it appears that documentation about resources import is missing on most resource type.

To be able to import my existing resources in my terraform state, I need to read sourcecode for each resource type I need to import to figure out how to import resources 👎 .

**Comment by yomovh** [comment]
@xtof-osd : I have pushed a PR 2 weeks ago, it is still in review but I think it will make its way  to the next release
