### ISSUE TITLE
[FEATURE] add displayName to ovh_dedicated_server

### ISSUE THREAD

**Issue by dilchenko** [ovh/terraform-provider-ovh#431]
### Description

`data.ovh_dedicated_server` returns the same data - which is `service_name` - for both `id` and `name` parameters. Which is expected, as both are set to the same value in the provider code:

- id: https://github.com/ovh/terraform-provider-ovh/blob/master/ovh/data_dedicated_server.go#L198
- name: https://github.com/ovh/terraform-provider-ovh/blob/master/ovh/data_dedicated_server.go#L206

It looks like additional API calls are required to fetch the custom server name as it is set in the portal, [community forums link](https://community.ovh.com/en/t/fetching-and-setting-custom-server-name-via-api/10041/2).

### Affected Resource(s) and/or Data Source(s)

* `ovh_dedicated_server`

### Potential Terraform Configuration

```
$ terraform plan
...
+ id                             = "ns1234567.ip-11-222-33.net"
...
+ name                           = "ns1234567.ip-11-222-33.net"
```

What is expected:

```
$ terraform plan
...
+ id                             = "ns1234567.ip-11-222-33.net"
...
+ name                           = "MyAwesomeServerName"
```

### Additional context

`ovh.tf`:

```hcl
data "ovh_dedicated_servers" "ovh_servers_list" {}

data "ovh_dedicated_server" "ovh_server" {
  for_each = toset(data.ovh_dedicated_servers.ovh_servers_list.result)
  service_name = each.key
}
```

`outputs.tf`:

```hcl
output "ovh_server_ids" {
  value = data.ovh_dedicated_servers.ovh_servers_list.*.result
}
output "ovh_server_names" {
  value = [ for server_id, server_details in data.ovh_dedicated_server.ovh_server: server_details.name ]
}
```

**Comment by amstuta** [comment]
@dilchenko just added a field `display_name` to the datasource.
