### ISSUE TITLE
[New Resource] DedicatedServerBringYourOwnImage

### ISSUE THREAD

**Issue by Eclion** [ovh/terraform-provider-ovh#450]
### Description

We would like to request the addition of this resource so we can automate the installation of our pre-setup OS.

A [PR regarding the implementation of this resource](https://github.com/ovh/terraform-provider-ovh/pull/434) has been created.

### Requested Resource(s) and/or Data Source(s)

* ovh_dedicated_server_bringyourownimage

### Potential Terraform Configuration

```hcl
data ovh_dedicated_server "server" {
  service_name = "nsxxxxxxx.ip-xx-xx-xx.eu"
  boot_type    = "harddisk"
}
resource ovh_dedicated_server_bringyourownimage "os_install" {
  service_name = data.ovh_dedicated_server.server.name
  url = "https://url_to_your_server/your_image.qcow2"
  type = "qcow2"
  config_drive {
    enable = true
    hostname = "my-server"
  }
}
```

**Comment by yomovh** [comment]
Closing the issue since the API route will be deprecated (see this [comment](https://github.com/ovh/terraform-provider-ovh/pull/434#issuecomment-1688238899) on the associated PR)
