### ISSUE TITLE
[FEATURE] Hardware Specifications datasource

### ISSUE THREAD

**Issue by Eclion** [ovh/terraform-provider-ovh#476]
### Description

In order to correctly register our hosts into our inventory using Terraform, we would like to know if it would be possible to request (and even help for the implementation) of the hardware specification datasource (endpoint: `/dedicated/server/%s/specifications/hardware`)

### Requested Data Source

* ovh_dedicated_server_hardware_specifications

**Comment by amstuta** [comment]
@Eclion datasource `ovh_dedicated_server_specifications_hardware` has been added, don't hesitate to give it a try.

**Comment by Eclion** [comment]
Hello @amstuta,
Works great, thank you very much!
