### ISSUE TITLE
[BUG] Trying to create object storage with high performance storage class

### ISSUE THREAD

**Issue by thoefkens** [ovh/terraform-provider-ovh#502]
### Describe the bug
I seem to be unable to create an object storage with storage class "high".
How can I use terraform to create an aws_s3_bucket with the high performance API?

### Terraform Version

1.0.57

### Affected Resource(s)

- aws_s3_bucket

**Comment by yomovh** [comment]
Hello,

Thanks for your issue. 
Did you had a look at that example => https://github.com/yomovh/tf-at-ovhcloud/tree/main/s3_bucket_only ?

But providing the high perf endpoint as variable it should be OK. 
See this [page](https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047393) for the list of the endpoint per region.

**Comment by yomovh** [comment]
I will close the issue, please reopen it if my answer is not helping
