### ISSUE TITLE
[FIX] Ability to set auto scaling setting on node pool

### ISSUE THREAD

**Issue by ccleouf66** [ovh/terraform-provider-ovh#506]
### Description

Is your feature request related to a problem? Please leave a brief description of the requested change.
Using kubectl I can edit the nodepool resource to configure the auto-scaling settings like:
```json
autoscaling": {
    "scaleDownUnneededTimeSeconds": 600,
    "scaleDownUnreadyTimeSeconds": 1200,
    "scaleDownUtilizationThreshold": "0.5"
  },
```
On Terraform provider I can't set these settings

### Affected Resource(s) and/or Data Source(s)

ovh_cloud_project_kube_nodepool

### Potential Terraform Configuration

"scaleDownUnneededTimeSeconds": (Optional) default 600,
"scaleDownUnreadyTimeSeconds": (Optional) default 1200,
"scaleDownUtilizationThreshold": (Optional) default "0.5"

**Comment by yomovh** [comment]
Thanks for your issue, I have redirected it to the product team.

**Comment by antonin-a** [comment]
Hello @ccleouf66, thank you for raising this issue, we will work on it !
