### ISSUE TITLE
[FEATURE] Resource ovh_cloud_project_network_private_subnet needs an option to create an internet gateway

### ISSUE THREAD

**Issue by kovanostra** [ovh/terraform-provider-ovh#509]
### Description

Currently, when using the ovh_cloud_project_network_private_subnet resource with no_gateway=false, I don't have the option to create an Internet Gateway and to associate it with the subnet. Also it is very confusing that OVH seems to use the Gateway name to refer to both a SNAT gateway and an internet Gateway. Then in the terraform documentation there is no clarification on which gateway you are referring to. This might be intuitive for network experts, but not all the terraform developers are such, so it might always be best to clarify.

1. As a developer I would like to either have a specific resource to create an Internet Gateway or an option to create an Internet Gateway inside ovh_cloud_project_network_private_subnet. 
2. The option name "no_gateway" is a bit confusing. It would be way better and intuitive in its use to name it just "gateway".
3. In the documentation it would be also useful to mention that the IP of the Gateway is decided from the IPs outside the range of the "start"-"end" options of the resource.

### Affected Resource(s) and/or Data Source(s)

* ovh_cloud_project_network_private_subnet

### Potential Terraform Configuration

No changes to the configuration if the feature is implemented inside the resource_cloud_project_network_private_subnet resource.

**Comment by yomovh** [comment]
Hello @kovanostra and thanks for your issue. 

A recommended work around is to use directly the openstack provider along with the ovh provider (we support it as well), this will you bring a lot of flexibility in your network choices.

You can find examples that are using those 2 providers in one terraform script in this repo https://github.com/yomovh/tf-at-ovhcloud 

Also I recommend this [documentation page](https://help.ovhcloud.com/csm/fr-terraform-at-ovhcloud?id=kb_article_view&sysparm_article=KB0054776) that guides you in choosing the provider & resources from the Control Panel concepts.

**Comment by amstuta** [comment]
Hello @kovanostra, the following [PR](https://github.com/ovh/terraform-provider-ovh/pull/571)  adds the resource `ovh_cloud_project_gateway`, does that fit your needs ?

**Comment by amstuta** [comment]
Closing this issue since `ovh_cloud_project_gateway` is available, don't hesitate to open a new one if needed.
