### ISSUE TITLE
[FEATURE] Manage mail addresses aliases in MX Plan

### ISSUE THREAD

**Issue by seboss666** [ovh/terraform-provider-ovh#530]
### Description

Manage various aspects of emails related objects, particularly aliases on a mail account. As we can't use dynamic aliases (you know, such convenient "toto+1234@domain.tld"), we need to declare them through the web manager or via API. Managing them through terraform would be super neat. I personnally have more than 30 aliases and it keeps growing every week.

### Affected Resource(s) and/or Data Source(s)

May be 

* ovh_email_mxplan_account_alias

### Potential Terraform Configuration

As documented [in the api](https://eu.api.ovh.com/console/#/email/mxplan/%7Bservice%7D/account/%7Bemail%7D/alias~GET), the resource (and data) should need these parameters:

- mxplan_service_name (can be controlled/retrieved via https://eu.api.ovh.com/console/#/email/mxplan~GET)
- mxplan_service_email (can be controlled/retrieved via https://eu.api.ovh.com/console/#/email/mxplan/{service}/account/{email}~GET)

### Additional context

In terraform "language", creation of such resource could be : 
```hcl
resource "email_mxplan_account_alias" "alias1" {
  mxplan_service_name  = "mxplan-xxxxxxx-1"
  mxplan_service_email = "user@domain.tld"   
  alias_name = "alias1"
}
```

This is a bonus, but for better management, the other objects (mxplan, email) could exist as data sources, at least the mxplan so you could create a list of emails account to lookup into ?

**Comment by yomovh** [comment]
Thanks for your issue. I have redirected it to the email product team.

**Comment by yomovh** [comment]
Hello @seboss666 ,

The terraform provider is currently not a priority for the email product. Hence, I will close the issue as not planned.
