### ISSUE TITLE
[BUG] Terraform + GitHub Actions = Can't create public cloud project and loss of project quota

### ISSUE THREAD

**Issue by aaurizon** [ovh/terraform-provider-ovh#554]
### Describe the bug

We can't create a Public Cloud Project with Terraform from Github Actions with hashicorp/setup-terraform@v3

I have uploaded an example: https://github.com/aaurizon/ovh-project

A simple code on https://github.com/aaurizon/ovh-project/blob/main/main.tf

Runned workflow : https://github.com/aaurizon/ovh-project/actions/runs/7832468758

It's working with Terraform CLI on Windows and Debian
But when we create it from GitHub Actions with "hashicorp/setup-terraform@v3"
It happend that the order is canceled and we lose 1 project quota for ever

I lost some account where I can't anymore create projects because i'm at 3/3 quota and I have 0 projects...

### Terraform Version

Terraform v1.7.3
on linux_amd64
+ provider registry.terraform.io/ovh/ovh v0.36.1
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.54.1

From GitHub Actions Workflow uses hashicorp/setup-terraform@v3

### OVH Terraform Provider Version

- Finding latest version of ovh/ovh...
- Finding latest version of terraform-provider-openstack/openstack...
- Installing ovh/ovh v0.36.1...
- Installed ovh/ovh v0.36.1 (signed by a HashiCorp partner, key ID F56D1A6CBDAAADA5)
- Installing terraform-provider-openstack/openstack v1.54.1...
- Installed terraform-provider-openstack/openstack v1.54.1 (self-signed, key ID 4F80527A391BEFD2)

### Affected Resource(s)

- ovh_cloud_project
- ovh_order_cart_product_plan
- ovh_order_cart

### Terraform Configuration Files

```hcl
https://github.com/aaurizon/ovh-project/blob/main/main.tf
```

### Debug Output

https://github.com/aaurizon/ovh-project/actions/runs/7832468758/job/21371227587

### Panic Output

N/A

### Expected Behavior

Create Public Cloud Project

### Actual Behavior

Order Canceled
Project Not Created
Lost 1 Project Quota for EVER (we're limited to 3 projects, do it 3 three times and you will not be able to create new project anymore)

### Steps to Reproduce

1. `copy my repository on your github https://github.com/aaurizon/ovh-project`
2. `Setup repository variable OVH_ENDPOINT = ovh-eu`
3. `Setup repository variable OVH_APPLICATION_KEY`
4. `Setup repository secret OVH_APPLICATION_KEY`
5. `Setup repository secret OVH_CONSUMER_KEY`
6. `Run Workflow Bootstrap`
7. `Congratulations, the project wasn't created and you lost 1 project quota`

### References

N/A

### Additional context

2 months i try to explain that to the support ovh, but they do nothing, they don't call devs and they don't help :)

**Comment by amstuta** [comment]
Hi @aaurizon , there must have been a transient issue on the order API, could you please try again ?

**Comment by amstuta** [comment]
Closing this issue as the problem should not happen again, don't hesitate to reopen it if the problem persists.
