### ISSUE TITLE
[DOCS] Import a vRack

### ISSUE THREAD

**Issue by vparpoil** [ovh/terraform-provider-ovh#618]
Following this issue https://github.com/ovh/terraform-provider-ovh/issues/512, this PR https://github.com/ovh/terraform-provider-ovh/pull/513 has added documentation on how to import a vrack.
However, it's really complicated in real life to find the vrack `order_id`.
My account has about 1 000 entries in the orders page (https://www.ovh.com/manager/#/dedicated/billing/orders/orders)

Please provide a more straightforward way to import a vrack or to find the associated `order_id`

[Edit] later on the [documentation](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/vrack_cloudproject#import) : when importing the link between a vrack and a cloud project, you need to provide the `attach_id`, which is not documented at all, and not available using Ovh API.

**Comment by amstuta** [comment]
@vparpoil thanks for opening this issue, we'll check shortly what can be done to simplify the import of a vrack and its link.

**Comment by vparpoil** [comment]
I finally found the order id somewhere. Using openstack Ids may be an idea ? They are easily accessible using openstack CLI

**Comment by amstuta** [comment]
I still think what you said is valid, we should be able to import a vrack using its ID instead of it's `orderID`. 

For the attachment, we should be able to retrieve everything using only OVH API and not rely on the openstack cli, we'll check what can be done.

**Comment by amstuta** [comment]
Closing this issue, in the next release:
- a vRack can be imported using its ID (instead of the orderID)
- Doc of import of `ovh_vrack_cloudproject` has been updated, `attach_id` is not even needed.
