### ISSUE TITLE
[BUG] Impossible to terraform apply if an instance is in rescue

### ISSUE THREAD

**Issue by vparpoil** [ovh/terraform-provider-ovh#632]
If an instance is in rescue, terraform apply gives the following output : 
```
│ Error: Invalid power_state for instance RETRACTED: RESCUE
│ 
│   with openstack_compute_instance_v2.RETRACTED[0],
│   on main.tf line 113, in resource "openstack_compute_instance_v2" "RETRACTED":
│  113: resource "openstack_compute_instance_v2" "RETRACTED" {
```

**Comment by amstuta** [comment]
Hello @vparpoil, could you share the config you use and the actions you took (for ex, how did your instance end up in rescue) ?

**Comment by amstuta** [comment]
OK, after digging a bit it seems that you can't put your instance in rescue mode from Terraform using the openstack provider, so you can't do the reverse either (re-activate the instance). So in your case you will have to reboot your instance from the OVH manager to be able to `terraform apply` again.

I invite you to open an issue directly on the Openstack provider repository if you think this behavior should be changed.
