### ISSUE TITLE
Resource "ovh_domain_zone"

### ISSUE THREAD

**Issue by NotJustPizza** [ovh/terraform-provider-ovh#64]
Is it possible to implement "domain_zone" as regular read/write resource with possibility to change "name_servers" and "dnssec_supported" fields ?

**Comment by dantefromhell** [comment]
> "dnssec_supported" 

Please correct me if my assumption is wrong, but I read this resource as "is DNSSEC technically possibly with the registry".

Nevertheless (at least read/ ideally read/write) field for detecting and/or changing current DNSSEC configuration would be super helpful.

**Comment by yomovh** [comment]
Hello @dantefromhell  and thanks for this comment.

Since the issue is old and the domain_zone is implemented. Can I ask you to open a new issue where you described what is missing in the ressource ? I will then redirect it to the product team. 

Thanks
