### ISSUE TITLE
[DOCS] Error with doc for datasource ovh_order_cart_product_plan in cloud_project resource on 0.44.0

### ISSUE THREAD

**Issue by jvdbc** [ovh/terraform-provider-ovh#650]
### Documentation link

https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project

### Description

hds_plan_code  = "certification.hds.2018"

=> An argument named "hds_plan_code" is not expected here

**Comment by amstuta** [comment]
Hello @jvdbc, thanks for opening this issue. You're right, there is a mismatch between the documentation and the datasource, we'll fix this shortly.
