### ISSUE TITLE
[BUG] ovh_cloud_project_kube_oidc crashed 

### ISSUE THREAD

**Issue by Fencherr** [ovh/terraform-provider-ovh#653]
### Describe the bug
Hi when i try to add google oidc to managed kubernetes service via terragrunt I got error below

### Terraform Version

Terraform v1.7.5
on linux_amd64
+ provider registry.terraform.io/ovh/ovh v0.44.0

### Affected Resource(s)

Please list the resources as a list, for example:
- ovh_cloud_project_kube
- ovh_cloud_project_kube_oidc

![image](https://github.com/ovh/terraform-provider-ovh/assets/41523274/721dfaba-3bad-4eeb-9a03-21d5124d47b1)

**Comment by amstuta** [comment]
Hello @Fencherr, could you provide us your TF plan so that we can reproduce your issue ?

**Comment by Fencherr** [comment]
Hi @amstuta when I plan  didn't see any error but when i apply it is giving me error which shared 

![image](https://github.com/ovh/terraform-provider-ovh/assets/41523274/3eda1ffd-956f-41ac-abfa-778971bca920)

![image](https://github.com/ovh/terraform-provider-ovh/assets/41523274/d7197878-173a-4e51-ba51-cf5fdb0c1669)

**Comment by amstuta** [comment]
@Fencherr I made the following PR that will avoid the panic: https://github.com/ovh/terraform-provider-ovh/pull/659. In the meantime, you should remove your empty `required` and 'group' claims since an empty string is not a valid value.
