### ISSUE TITLE
[FEATURE] Create Gateway Interface using the provider

### ISSUE THREAD

**Issue by neurovul** [ovh/terraform-provider-ovh#674]
### Description

Hello,

I created a Gateway with an Interface using the OVH web console and would like to achieve the same using Terraform.

I noticed that it is possible through the API console using the endpoint `/cloud/project/{serviceName}/region/{regionName}/gateway/{id}/interface`. However, I couldn't find a way to accomplish this using the Terraform provider.

When I run `terraform plan`, it detects a discrepancy between the current state and the desired configuration.

Is there a plan to add this feature to the Terraform provider, or am I overlooking an existing feature?

Best regards,

### Affected Resource(s) and/or Data Source(s)

Maybe the existant `ovh_cloud_project_gateway` or a new `ovh_cloud_project_gateway_interface`

_EDIT : I just find a PR which may be related to this feature https://github.com/ovh/terraform-provider-ovh/pull/358_

**Comment by amstuta** [comment]
Hello @neurovul, indeed PR #358 began the work to add resource `ovh_cloud_project_gateway_interface`.
We will resume the work on it as soon as possible and keep you posted here.

**Comment by neurovul** [comment]
Hello @amstuta, great, thank you
