### ISSUE TITLE
[FEATURE] : allow dedicated server displayName configuration

### ISSUE THREAD

**Issue by 131** [ovh/terraform-provider-ovh#684]
### Description
I want to update my server "displayName" using ovh_dedicated_server_update 

### Affected Resource(s) and/or Data Source(s)

* ovh_dedicated_server_update

### Potential Terraform Configuration

```
resource "ovh_dedicated_server_update" "server" {
  service_name = data.ovh_dedicated_server.metal.service_name
  displayName = "use-this-as-name"

  boot_id      = data.ovh_dedicated_server_boots.harddisk.result[0]
  monitoring   = false
  state        = "ok"
}

**Comment by amstuta** [comment]
Hello @131, I'm not sure what field you would like to update in the API ?
There is indeed a `name` field in dedicated servers, but I think it is the `serviceName` (the same as the one used as path parameter), and it is not editable.

**Comment by 131** [comment]
THe "displayName"

**Comment by e-gautier** [comment]
related data field https://registry.terraform.io/providers/ovh/ovh/latest/docs/data-sources/dedicated_server#display_name

**Comment by amstuta** [comment]
OK I see, since the displayName cannot be edited from the dedicated server section directly, we'll have to add a call to `PUT /services/{serviceId}` to update it. We will add this as soon as possible.

**Comment by 131** [comment]
That's great, you are the best
thanks a lot 💯
