### ISSUE TITLE
[FEATURE] [Logs Data Platform] Setting the retention period of a logs data stream

### ISSUE THREAD

**Issue by pgillet** [ovh/terraform-provider-ovh#687]
### Description

It is not possible to set the retention period of a logs data stream within Terraform, among the possible values in the OVHcloud console: `14 days`, `a month`, `3 months` or `a year`.

### Affected Resource(s) and/or Data Source(s)

* ovh_dbaas_logs_output_graylog_stream

### Potential Terraform Configuration

Add a `retention_period` or similar argument to the resource `ovh_dbaas_logs_output_graylog_stream`.

### Additional context

There is indeed the `retention_id` argument which allows to set the retention period but there is no Terraform resource/data source mapped to the endpoint ` /dbaas/logs/{serviceName}/cluster/{clusterId}/retention` that would retrieve such an ID.

**Comment by pgillet** [comment]
That's purrfect 😸 

Always impressed and grateful for OVH's responsiveness.
You guyz are the best 👍 

When will it be released?

**Comment by amstuta** [comment]
That's great to hear 😃 we'll try to make a release this afternoon, and if not possible on Monday ;)

**Comment by amstuta** [comment]
@pgillet version `0.47.0` has been released !

**Comment by 131** [comment]
I find it difficult to find the cluster_id , i end up using 
```

data "ovh_dbaas_logs_cluster_retention" "retention_3months" {
  service_name = "ldp-ra-XXXX"
  cluster_id   =  substr(data.ovh_dbaas_logs_cluster.logstash.id, -36, 36)
  duration     = "P90D"
}
```

Is there a better way to access the cluster id ?

**Comment by amstuta** [comment]
@131 In fact I just noticed that the field `cluster_id` should be set in the datasource `ovh_dbaas_logs_cluster` and it is not.

I just made this PR to fix this so you don't need to use `substr` on the id itself ;)

https://github.com/ovh/terraform-provider-ovh/pull/694

**Comment by 131** [comment]
Thank you very much, i'll be waiting for the next release train
