### ISSUE TITLE
[FEATURE] resource_cloud_project_user_s3_policy - add refresh for policy property

### ISSUE THREAD

**Issue by mborne** [ovh/terraform-provider-ovh#701]
### Description

After facing HTTP issues applying changes on a lot of resource_cloud_project_user_s3_policy, we have noticed that terraform module was not able to detect inconsistency between `resource_cloud_project_user_s3_policy` and OVH API equivalent (`GET /cloud/project/{serviceName}/user/{userId}/policy`).

### Affected Resource(s) and/or Data Source(s)

* resource_cloud_project_user_s3_policy

### Potential Terraform Configuration

No additionnal parameters changes requests. "refresh" should occur on running "terraform refresh" or "terraform plan" for `resource_cloud_project_user_s3_policy` resources.

### Additional context

* Not urgent, bypassed adding "V2" suffix in "Sid" to force update.
* An example of HTTP error followed by "Your infrastructure matches the configuration" :

![retry-on-http-error](https://github.com/user-attachments/assets/222107d1-6b82-4a69-a3e3-0649135f278a)

**Comment by mborne** [comment]
Trying to remove and re-import a given state, it seems that the problem concerns the JSON "policy" field :

```tf
resource "ovh_cloud_project_user_s3_policy" "user_rw_policy" {
    id           = "OK"
    service_name = "OK"
    user_id      = "OK"
    # policy       = MISSING AFTER IMPORT
}
```

It might be a bug.

**Comment by amstuta** [comment]
Hello @mborne, thanks for your issue. The value returned by the API for property `policy` is indeed ignored and it doesn't seem right.
We will fix this quickly.

**Comment by amstuta** [comment]
Fix has been merged and will be released in the next few days, don't hesitate to reopen an issue if you have remaining issues.

**Comment by mborne** [comment]
Thank you. We will check this fix at the next release.
