### ISSUE TITLE
[FEATURE] change whole zone information at one go

### ISSUE THREAD

**Issue by Kamilcuk** [ovh/terraform-provider-ovh#705]
### Description

The https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/ovh_domain_zone_record allows to change _single entry_. This is odd. I would want to control whole zone at one go using https://eu.api.ovh.com/console/?section=%2Fdomain&branch=v1#post-/domain/zone/-zoneName-/import .

### Affected Resource(s) and/or Data Source(s)

"Domain names".

### Potential Terraform Configuration

```
resource "ovh_domain_zone_content" "example" {
  zonefile = file("./example.zone")
}
```

### Additional context

Thank you for the plugin, it is amazing.

**Comment by amstuta** [comment]
Hello @Kamilcuk, this would indeed be a nice feature to add to the provider. We'll try to add this resource shortly.

**Comment by Kamilcuk** [comment]
Hi, that is great. I manage whole zone files, cause it's easier for me to manage all the spf/srv/mx entries. Curently I have a small python script that calls the API. Note that when you call import API, and then get zone back with export API, the returned zone file is not exactly the same, from memory, whitespaces and some numbers differ. All I can say is good luck, have fun and you're great.

**Comment by amstuta** [comment]
PR has been merged, we'll release the provider soon :)
