### ISSUE TITLE
[FEATURE][Logs Data Platform] Dedicated input autoscaling

### ISSUE THREAD

**Issue by pgillet** [ovh/terraform-provider-ovh#714]
### Description

It is not possible to enable autoscaling of the number of instances for a dedicated input (Logstash) within Terraform.

### Affected Resource(s) and/or Data Source(s)

* `ovh_dbaas_logs_input`

### Potential Terraform Configuration

- Add a boolean argument `autoscaling_enabled` with the value `false` by default.
- Along with arguments `min_nb_instance` and `max_nb_instance`

**Comment by amstuta** [comment]
Hello @pgillet, indeed these parameters are missing, so we'll add them quickly !

**Comment by pgillet** [comment]
Purrfect! Many thanks 💯 👍

**Comment by pgillet** [comment]
Worked like a charm! 🥇
