### ISSUE TITLE
[FEATURE] make default namespace of m3db configurable

### ISSUE THREAD

**Issue by markush81** [ovh/terraform-provider-ovh#752]
### Description

Add https://eu.api.ovh.com/console/?section=%2Fcloud&branch=v1#put-/cloud/project/-serviceName-/database/m3db/-clusterId-/namespace/-namespaceId- for default namespace of m3db to terraform

### Affected Resource(s) and/or Data Source(s)

* ovh_cloud_project_database
* ovh_cloud_project_database_m3db_namespace

**Comment by BellionBastien** [comment]
Hello @markush81,

We are going to update the `ovh_cloud_project_database_m3db_namespace` resource in order to automatically map any resource with the field `name` set to "default" to the default namespace created with the service.

This will allow you to configure your default namespace.
