### ISSUE TITLE
[BUG] Importing existing domain zone forces replacement

### ISSUE THREAD

**Issue by m-wrzesien** [ovh/terraform-provider-ovh#753]
### Describe the bug
I was trying to import my domain zones, which were created manually few years ago.
Problem is, that terraform wants to replace them due to conflict on `plan` and `ovh_subsidiary` fields of `ovh_domain_zone` resource.

### Terraform Version

v1.9.7

### OVH Terraform Provider Version

v0.51.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `ovh_domain_zone`

### Terraform Configuration Files

Based on [example usage of ovh_domain_zone:](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/domain_zone)
```hcl
terraform {
  required_providers {
    ovh = {
      source  = "ovh/ovh"
      version = "~> 0.51"
    }
  }
}

data "ovh_me" "myaccount" {}

data "ovh_order_cart" "mycart" {
  ovh_subsidiary = data.ovh_me.myaccount.ovh_subsidiary
}

data "ovh_order_cart_product_plan" "zone" {
  cart_id        = data.ovh_order_cart.mycart.id
  price_capacity = "renew"
  product        = "dns"
  plan_code      = "zone"
}
resource "ovh_domain_zone" "zone" {
  for_each       = toset(["DOMAIN"])
  ovh_subsidiary = data.ovh_order_cart.mycart.ovh_subsidiary

  plan {
    duration     = data.ovh_order_cart_product_plan.zone.selected_price.0.duration
    plan_code    = data.ovh_order_cart_product_plan.zone.plan_code
    pricing_mode = data.ovh_order_cart_product_plan.zone.selected_price.0.pricing_mode

    configuration {
      label = "zone"
      value = each.value
    }

    configuration {
      label = "template"
      value = "minimized"
    }
  }
}
```

### Expected Behavior

Domain zone is imported and next terraform plan only updates its fields.

### Actual Behavior

After import terraform wants to replace the resource.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform import 'ovh_domain_zone.zone["DOMAIN"]' ORDER_ID`
1. `terraform apply`

### Temporary workaround
```hcl
lifecycle {
    ignore_changes = [
      plan,
      ovh_subsidiary
    ]
  }
```

### References

- GH-734 - also has similar problem with `ovh_subsidiary`

### Additional context

`terraform apply` output after import:

```
Terraform will perform the following actions:

  # ovh_domain_zone.zone["DOMAIN"] must be replaced
-/+ resource "ovh_domain_zone" "zone" {
      ~ dnssec_supported = true -> (known after apply)
      ~ has_dns_anycast  = true -> (known after apply)
      ~ id               = "REDACTED" -> (known after apply)
      ~ last_update      = "REDACTED" -> (known after apply)
      ~ name             = "DOMAIN" -> (known after apply)
      ~ name_servers     = [
          - "ns200.anycast.me",
          - "dns200.anycast.me",
        ] -> (known after apply)
      + ovh_subsidiary   = "PL" # forces replacement
      ~ urn              = "urn:v1:eu:resource:dnsZone:DOMAIN" -> (known after apply)

      ~ order (known after apply)
      - order {
          - date            = "REDACTED" -> null
          - details         = [
              - {
                  - description     = "REDACTED"
                  - domain          = "DOMAIN"
                  - order_detail_id = REDACTED
                  - quantity        = "1"
                },
              - {
                  - description     = "REDACTED"
                  - domain          = "DOMAIN"
                  - order_detail_id = REDACTED
                  - quantity        = "1"
                },
            ] -> null
          - expiration_date = "REDACTED" -> null
          - order_id        = ORDER_ID -> null
        }

      + plan { # forces replacement
          + duration     = "P1Y"
          + plan_code    = "zone"
          + pricing_mode = "default"

          + configuration {
              + label = "zone"
              + value = "DOMAIN"
            }
          + configuration {
              + label = "template"
              + value = "minimized"
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

**Comment by amstuta** [comment]
Hello @m-wrzesien, thanks for opening this issue.

We are aware of this problem and are currently working on a fix that won't require you to provide the `plan` and `ovh_subsidiary` attributes when importing a resource.
You will thus be able to import your resource using only the "real" attributes and not the ones used at order time.

The PR should be opened today, I'll link it to this issue.

**Comment by m-wrzesien** [comment]
Hi @amstuta, that's great to hear.
In that case i will wait for it.

**Comment by m-wrzesien** [comment]
I've tested the new release and was able to use it, but had one mirror issue.
This might be helpful to other users of the provider.

I've tried to import zone as described in provider docs:
```
terraform plan -generate-config-out=zone.tf
```

Following configuration is generated for my zones:
```
# __generated__ by Terraform
# Please review these resources and move them into your main configuration files.

# __generated__ by Terraform from "DOMAIN"
resource "ovh_domain_zone" "zone1" {
  ovh_subsidiary = null
}
```
Import worked fine, but Terraform Language Server (via VS Code extension) didn't like that `plan` was missing and throwed:
```
Too few blocks specified for "plan": At least 1 block(s) are expected for "plan"
```

For this to go away i needed to modify code a bit:
```
resource "ovh_domain_zone" "zone1" {
  # nulls in ovh_subsidiary and plan is workaround for imported zones
  ovh_subsidiary = null
  dynamic "plan" {
    for_each = []
    content {
      plan_code    = null
      duration     = null
      pricing_mode = null
    }
  }
}
```

**Comment by amstuta** [comment]
Thanks for your feedback @m-wrzesien.

It may just come from your Terraform extension not being reloaded ? I didn't manage to reproduce this morning using version `1.0.0`.
