### ISSUE TITLE
r/ovh_domain_zone_record, r/ovh_domain_zone_redirection silent errors

### ISSUE THREAD

**Issue by yanndegat** [ovh/terraform-provider-ovh#76]
### Affected Resource(s)

- ovh_domain_zone_record
- ovh_domain_zone_redirection

### Description

The way some resources are handled by the OVH API is:
- do changes (POST/PUT/DELETE)
- launch a "refresh" task so that changes are applied

But on some resources, you cannot schedule more than one refresh at a time.
So you can encounter concurrency issues regarding refreshes, moreover by the way
terraform runs its changes in parallel

Currently, in "domain_zone" refreshes, refresh actions errors are silenced, so it seems that changes
are applied but factually, it may have failed.

We should handled refresh tasks for domain zones the way it is handled for the loadbalancing resources: as a separated & explicit resource.

**Comment by yanndegat** [comment]
@radeksimko

**Comment by iptizer** [comment]
Might be related to this. I am doing the following to set up all my subdomains:

```hcl
variable "subdomains_mydomain" {
  default = ["git","auth","prometheus","alertmanager","chat","mqtt", "cloud","monitoring","smtp","pop3","imap","jaeger","ldap","code","hub","grafana","tt-rss","phpmyadmin","phppgadmin","www","terraformtest","rstudio","code" ]
}

resource "ovh_domain_zone_record" "mydomain_subdomains" {
    for_each = toset( var.subdomains_mydomain )
    zone = "mydomain.com"
    subdomain = each.key
    fieldtype = "CNAME"
    ttl = local.ttl
    target = "mydomain.com."
}
```

Now, some time later after I successfully applied this, I get lots of the following errors:

```shell
Error: Unable to find zone record 123456789 after retries: Unable to find zone record mydomain.com/123456789 after retries: Error 404: "The requested object (id = 123456789) does not exist"
```

Could this be related as there have been various optimizations to Terraform now with 0.12?

**Comment by gaetanfl** [comment]
We went through the same errors. Sometimes id of zone record are changed. The only way we managed to get rid of this is by doing `terraform state pull > broken_state.json` change ids in the json and then `terraform state push fixed_state.json`

**Comment by iptizer** [comment]
What was you solution on finding the right ids? I played with python to walk over all the resources and gather the data. Which worked, but in the end, to make it final, I chose to delete all records via web console and let Terraform recreate all resources.

Do you think this is done by OVH? But this totally destroys using the APi, does it? Even when not using Terraform, but using "classic" programmatic approach.

**Comment by gaetanfl** [comment]
@iptizer I did the same with some scripts and a lot of manual operations since our zone is not that big. We did no change in the zone manually nor using terraform so I guess it's OVH doing some refresh or some changes on infrastructure behind.
I don't understand how a more than one time thing with the api is supposed to work. I contacted their support on twitter, waiting for an answer

**Comment by dlecan** [comment]
Thank you @gaetanfl for the commands with `terraform state ...` to handle this horrible use case: the stable, permanent ids of OVH DNS resources have been changed!
It happens 2 or 3 times a year for me (handling 20 domains). This is a real pain with OVH DNS.

>I contacted their support on twitter, waiting for an answer

I have never got answers to the same questions.

**Comment by cchaudier** [comment]
Hello,

I've the same problem.
Please OVH fixe this issue  🙏

**Comment by vhurtevent** [comment]
Hello,

after few messages through OVH support, it seems I finaly got the answer : when using plain text edition of the DNS zone in the OVH manager, the whole zone is reimported and DNS records get new IDs.

I asked for warning user when using this functionnality.

So, never user TF and plain text zone edition on the same zone.

**Comment by cchaudier** [comment]
> So, never user TF and plain text zone edition on the same zone.

I think I have the same probleme.
Thank's @vhurtevent.

**Comment by amstuta** [comment]
Closing this issue as the source of the problem has been identified.
