### ISSUE TITLE
[BUG] Cannot use OVH S3 bucket to store terraform state

### ISSUE THREAD

**Issue by ant1g** [ovh/terraform-provider-ovh#762]
### Describe the bug

I am using terraform with the OVH provider and I am trying to have the terraform state stored on an OVH S3 bucket.
I have followed this tutorial: https://help.ovhcloud.com/csm/en-public-cloud-compute-terraform-high-perf-object-storage-backend-state?id=kb_article_view&sysparm_article=KB0051345

I have configured everything correctly but I am getting the following error when doing a `terraform init --reconfigure` (because I am coming from a local terraform state that I want to move to an S3 bucket:
```
Initializing the backend...
╷
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata,
│ exceeded maximum number of attempts, 3, request send failed, Get
│ "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect:
│ no route to host
│ 
```

### Terraform Version

```
Terraform v1.9.7
on linux_amd64
```

### OVH Terraform Provider Version

```
ovh/ovh v0.50.0
terraform-provider-openstack/openstack v3.0.0
```

### Affected Resource(s)

Please list the resources as a list, for example:
- s3
- terraform / provider

If this issue appears to affect multiple resources, it may be an issue with [Terraform's core](https://github.com/hashicorp/terraform).

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.9.7"

  required_providers {
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "3.0.0"
    }
    ovh = {
      source  = "ovh/ovh"
      version = "0.50.0"
    }
  }

  # Currently broken
  backend "s3" {
    bucket = <CONFIG>
    key    = <CONFIG>
    region = "GRA"
    endpoints = {
      s3 = "https://s3.gra.perf.cloud.ovh.net/"
    }
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_s3_checksum            = true
  }
}

# Configure the OpenStack provider hosted by OVHcloud
provider "openstack" {
  auth_url    = "https://auth.cloud.ovh.net/v3/"
  domain_name = "default"
  alias       = "ovh"
  region      = "GRA11"
  tenant_id   = <CONFIG>
  tenant_name = <CONFIG>
  user_name   = <CONFIG>
  password    = <CONFIG>
}

provider "ovh" {
  alias              = "ovh"
  endpoint           = <CONFIG>
  application_key    = <CONFIG>
  application_secret = <CONFIG>
  consumer_key       = <CONFIG>
}
```

### Debug Output

```
Initializing the backend...
╷
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata,
│ exceeded maximum number of attempts, 3, request send failed, Get
│ "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect:
│ no route to host
│ 
```

### Expected Behavior

The state should have been stored on the ovh s3 bucket.

### Actual Behavior

Got an error

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Additional context

I have been able to use terraform otherwise, with storing the default locally (default behavior), to create VM or database resources, without a problem.

**Comment by amstuta** [comment]
Hello @ant1g, 

I personally made it work by defining `access_key` and `secret_key` in the backend definition. You can check the following doc: https://developer.hashicorp.com/terraform/language/backend/s3#secret_key , it is also possible to use environment variables.

Could you try and see if it solves your issue ? 

I used the following configuration:
```
backend "s3" {
      bucket = "bucket-name"
      key    = "terraform.tfstate"
      region = "gra"
      endpoints = {
        s3 = "https://s3.gra.perf.cloud.ovh.net/"
      }
      skip_credentials_validation = true
      skip_region_validation      = true
      skip_requesting_account_id  = true
      skip_s3_checksum            = true
      access_key = "the access key"
      secret_key = "the secret key"
    }
```

**Comment by ant1g** [comment]
Hello and thanks for the feedback.
What access_key and secret_key are we talking about here?
I have either:
OVH_APPLICATION_KEY
OVH_APPLICATION_SECRET
OVH_CONSUMER_KEY

**Comment by ant1g** [comment]
I managed, there are specific S3 users to be defined as well.
BTW, is there an up to date documentation that would actually highlight this particular configuration?

**Comment by amstuta** [comment]
Yes that's it, the `access_key` and `secret_key` are s3-specific and have nothing to do with the OVHcloud API credentials.

Regarding the documentation, we already plan to update it with the same information I gave you, but don't hesitate to make suggestions if you want to add more info !

**Comment by ant1g** [comment]
Thanks, I think we can close this ticket then!

**Comment by amstuta** [comment]
FYI, doc should be updated soon: https://github.com/ovh/docs/pull/7109 ;)
