### ISSUE TITLE
[BUG] Openstack random failures 'retries exhausted' when doing a terraform apply

### ISSUE THREAD

**Issue by ant1g** [ovh/terraform-provider-ovh#763]
### Describe the bug

I am using terraform with the OVH provider and I am experiencing random failures (`retries exhausted`) while doing a `terraform apply`. It fails to retrieve state information of my resources. If I retry a few times, it usually works.

```
╷
│ Error: Error retrieving <redacted> <redacted>: Get "https://volume.compute.gra11.cloud.ovh.net/v3/<redacted>/volumes/<redacted>": OpenStack connection error, retries exhausted. Aborting. Last error was: read tcp <redacted>:40722-><redacted>:443: read: connection reset by peer
```

### Terraform Version

```
Terraform v1.9.7
on linux_amd64
```

### OVH Terraform Provider Version

```
ovh/ovh v0.50.0
terraform-provider-openstack/openstack v3.0.0
```

### Affected Resource(s)

Please list the resources as a list, for example:
- terraform / provider

### Debug Output

```
Initializing the backend...
╷
│ Error: Error retrieving <redacted> <redacted>: Get "https://volume.compute.gra11.cloud.ovh.net/v3/<redacted>/volumes/<redacted>": OpenStack connection error, retries exhausted. Aborting. Last error was: read tcp <redacted>:40722-><redacted>:443: read: connection reset by peer
```

### Expected Behavior

No such error should appear. If there are any rate limiting, its configuration should be explained / documented somewhere.

### Actual Behavior

Got an error and I have to retry until it suceeds.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by amstuta** [comment]
Hello @ant1g , I'm sorry but we won't be able to help you here on issues related to the openstack APIs. 

If you continue experiencing this kind of random failures, don't hesitate to contact our support with helpful information such as request IDs, timestamps, reproducers, and they should be able to help you.

**Comment by ant1g** [comment]
OK, thanks, will do!
