### ISSUE TITLE
[FEATURE] Configure monthly billing for managed database

### ISSUE THREAD

**Issue by jnurkka** [ovh/terraform-provider-ovh#784]
### Description

Is your feature request related to a problem? Please leave a brief description of the requested change.

I would like to use monthly billed managed database services (mongodb)
I would like to configure my managed database services in terraform

Both of the above are not possible because I cant configure monthly billing in the terraform provider, at least not [according to the docs](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_database)

### Affected Resource(s) and/or Data Source(s)

* ovh_cloud_project_database

### Potential Terraform Configuration

If this request was implemented, what might the Terraform configuration look like? A best guess is helpful, even if you're unsure of exactly what the end result will look like. This helps maintainers and the community better understand how you (someone who is in need of this feature) envisions it.

[Similar as for Managed Kubernetes](https://registry.terraform.io/providers/ovh/ovh/latest/docs/resources/cloud_project_kube_nodepool#monthly_billed-2), I would expect to be able to set `monthly_billed = true` in my Terraform config.

### Additional context

Add any other context, HCL configuration or screenshots about the feature request here.

**Comment by amstuta** [comment]
Hello @jnurkka, thanks for opening this issue.

The parameter `monthly_billed` is not available on cloud databases because monthly billing is not available on the product itself (the price per month that you can see on our website when ordering a database is just a hint of what the total price will be for one month, but it doesn't affect the billing).

If it's a feature that you're really interested in, you can ask for it in our public roadmap here: https://github.com/ovh/public-cloud-roadmap :)

**Comment by jnurkka** [comment]
> Hello @jnurkka, thanks for opening this issue.
> 
> The parameter `monthly_billed` is not available on cloud databases because monthly billing is not available on the product itself (the price per month that you can see on our website when ordering a database is just a hint of what the total price will be for one month, but it doesn't affect the billing).
> 
> If it's a feature that you're really interested in, you can ask for it in our public roadmap here: https://github.com/ovh/public-cloud-roadmap :)

Oh, thats news to me 😬 The way it is represented is very misleading in the public cloud management console.
