### ISSUE TITLE
ovh_cloud_user should support role / roles arguments

### ISSUE THREAD

**Issue by tlvenn** [ovh/terraform-provider-ovh#88]
Hi,

Right now, it's not possible to manage the role(s) of a given user created with ovh_cloud_user. Even more problematic, the actual default role is `Administrator` while one would expect no role to be attached at all.

Thanks in advance.

**Comment by amstuta** [comment]
Hi @tlvenn , it is now possible to handle roles using resource `ovh_cloud_project_user`, and if no role is specified it doesn't seem to default to `administrator` (just tested locally). I'll thus close this issue, don't hesitate to reopen if needed.
