### ISSUE TITLE
Access Rights and Poor Documentation

### ISSUE THREAD

**Issue by Vad1mo** [ovh/terraform-provider-ovh#9]
Prior using the OVH provider, one need first [create an API token]( https://api.ovh.com/createToken/ ) IMHO it should be noted where to get the application_key, application_secret and consumer_key

The URL /createToken is hard to find and poorly documented. At lest be a bit kind with dev who now TF but not the specific Cloud Provider procedures.  

In addition to that it should also be documented what access rights are needed from this plugin. Right its /* on GET,POST,DELETE. After of hours of trying I couldn't find all the URL and requests. 

Btw. There is even an option where you could create a URL with arguments that would prefill the form with the right access rights:

e.g https://api.ovh.com/createToken/?GET=/*&POST=/*&PUT=/*&DELETE=/*

**Comment by guillermo-menjivar** [comment]
Wow you saved me soo much time! Thank you. I agree with the lack of recent documentation

**Comment by amstuta** [comment]
Closing this issue since the process is now explained in the `Provider configuration` part of the documentation, see https://github.com/ovh/terraform-provider-ovh/blob/master/website/docs/index.html.markdown#provider-configuration
