### ISSUE TITLE
create new public cloud Instance

### ISSUE THREAD

**Issue by scippio** [ovh/terraform-provider-ovh#91]
Is possible create new public cloud Instance? I can't find any info about that in documentation...

**Comment by DeWaRs1206** [comment]
@scippio OVH use Openstack, so you can use Openstack provider to create your instances:
https://www.terraform.io/docs/providers/openstack/index.html

https://docs.ovh.com/gb/en/public-cloud/how-to-use-terraform/

**Comment by scippio** [comment]
@DeWaRs1206 ok, thanks. I'll try it.

**Comment by Ruluk** [comment]
Suggestion: I think this would be great documentation to add in the verified OVH Terraform provider.

I, for one, started my research in the Terraform registry, not in the OVH website.

**Comment by amstuta** [comment]
@Ruluk you're right, and we're currently trying to add the maximum of resources in `terraform-provider-ovh`. 

In the meantime, this documentation states which provider to use for each need: https://help.ovhcloud.com/csm/en-gb-terraform-at-ovhcloud?id=kb_article_view&sysparm_article=KB0054612.
